package auction.network;

public enum MessageType {
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    FORGOT_PASSWORD_REQUEST,
    FORGOT_PASSWORD_RESPONSE,
    DEPOSIT_REQUEST,
    DEPOSIT_RESPONSE,
    BID_REQUEST,
    BID_RESPONSE,
    AUTO_BID_REQUEST,    // Client đăng ký Auto-Bid
    AUTO_BID_RESPONSE,   // Server xác nhận đăng ký
    AUTO_BID_CANCEL,     // Client hủy Auto-Bid
    GET_AUCTIONS_REQUEST,
    GET_AUCTIONS_RESPONSE,
    GET_BID_HISTORY_REQUEST,
    GET_BID_HISTORY_RESPONSE,
    CREATE_ITEM_REQUEST,
    CREATE_ITEM_RESPONSE,
    AUCTION_EXTENDED,
    AUCTION_CLOSED,
    NEW_BID,
    NOTIFICATION,
    ERROR,
    DELETE_AUCTION_REQUEST,
    DELETE_AUCTION_RESPONSE,
    GET_USERS_REQUEST,
    GET_USERS_RESPONSE,
    DELETE_USER_REQUEST,
    DELETE_USER_RESPONSE,
    UNKNOWN
}
